### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by wesleybvance** [nss-evening-cohort-21/InCRUDibles#2]
- [x] set up wireframe for homepage
- [x] wireframe for boards page
- [x] wireframe for individual pin details
- [x] wireframe for create/edit pin form
- [x] wireframe for create/edit board form

**Comment by gonzalez-aj** [comment]
A Tribe Called Wes(ley) aka TCDUB

**Comment by wesleybvance** [comment]
https://www.figma.com/file/WFw7x0oOBQEP4dRlcJmP9n/View-Pins%2FView-Community-Pins?node-id=0%3A1&t=2zfNwYMWg4roCbDw-1
