### ISSUE TITLE
Pintwist Figma Wireframe

### ISSUE THREAD

**Issue by gonzalez-aj** [nss-evening-cohort-21/InCRUDibles#25]
![pintwist-Figma-Wireframe](https://user-images.githubusercontent.com/114124374/215930863-2d30d1c5-e98f-45f2-8680-153095f64ff4.png)

**Comment by gonzalez-aj** [comment]
also please do not close this issue ticket <3 ty

**Comment by wesleybvance** [comment]
https://www.figma.com/file/WFw7x0oOBQEP4dRlcJmP9n/View-Pins%2FView-Community-Pins?node-id=0%3A1&t=2zfNwYMWg4roCbDw-1
